run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true

linters-settings:
  dupl:
    threshold: 100
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
  
  gci:
    local-prefixes: github.com/korya/vrata
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  
  gocyclo:
    min-complexity: 15
  
  godot:
    scope: declarations
    capital: false
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/korya/vrata
  
  mnd:
    checks: argument,case,condition,operation,return,assign
    ignored-numbers: 0,1,2,3
    ignored-functions: strings.SplitN
  
  govet:
    check-shadowing: true
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  
  lll:
    line-length: 140
  
  maligned:
    suggest-new: true
  
  misspell:
    locale: US
  
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  revive:
    rules:
      - name: exported
        arguments: [checkPrivateReceivers]
      - name: unreachable-code
      - name: unused-parameter
  
  testpackage:
    skip-regexp: (export|internal)_test\.go
  
  unparam:
    check-exported: false
  
  unused:
    check-exported: false
  
  whitespace:
    multi-if: false
    multi-func: false

linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - exhaustive
    - gci
    - goconst
    - gocritic
    - gocyclo
    - godot
    - gofmt
    - goimports
    - mnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

  disable:
    - deadcode
    - exportloopref
    - gomnd
    - structcheck
    - varcheck
    - maligned
    - interfacer

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - dupl
        - errcheck
        - gosec
    
    - path: cmd/
      linters:
        - gocyclo
        - mnd
        - depguard
    
    - path: example/
      linters:
        - mnd
        - goconst
        - depguard
        - errcheck
        - gosec
    
    - linters:
        - staticcheck
      text: "SA9003:"
    
    - linters:
        - lll
      source: "^//go:generate "

  exclude-use-default: false
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'
    - 'package comment should be of the form'
  
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false