version: 2

run:
  timeout: 5m
  issues-exit-code: 1
  tests: true
  modules-download-mode: readonly

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters-settings:
  depguard:
    rules:
      Main:
        allow:
          - $gostd
          - github.com/korya/vrata

  dupl:
    threshold: 100
  
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  exhaustive:
    check-generated: false
    default-signifies-exhaustive: false
  
  goconst:
    min-len: 2
    min-occurrences: 2
  
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
  
  gocyclo:
    min-complexity: 15
  
  godot:
    scope: declarations
    capital: false
  
  mnd:
    checks:
      - argument
      - case
      - condition
      - operation
      - return
      - assign
    ignored-numbers:
      - 0
      - 1
      - 2
      - 3
    ignored-functions:
      - strings.SplitN
  
  govet:
    enable:
      - shadow
    settings:
      printf:
        funcs:
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
  
  lll:
    line-length: 120
  
  
  misspell:
    locale: US
  
  nolintlint:
    allow-unused: false
    require-explanation: false
    require-specific: false
  
  prealloc:
    simple: true
    range-loops: true
    for-loops: false
  
  revive:
    rules:
      - name: exported
        arguments: [checkPrivateReceivers]
      - name: unreachable-code
      - name: unused-parameter
  
  testpackage:
    skip-regexp: (export|internal)_test\.go
  
  unparam:
    check-exported: false
  
  unused:
    field-writes-are-uses: true
    post-statements-are-reads: false
    exported-fields-are-used: true
    parameters-are-used: true
    local-variables-are-used: true
    generated-is-used: true
  
  whitespace:
    multi-if: false
    multi-func: false

formatters:
  gci:
    sections:
      - standard
      - default  
      - prefix(github.com/korya/vrata)
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/korya/vrata
  gosimple:

linters:
  enable:
    - bodyclose
    # - depguard
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - godot
    - mnd
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - prealloc
    - revive
    - unconvert
    - unparam
    - unused
    - whitespace

  disable: []

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - mnd
        - goconst
        - dupl
        - errcheck
        - gosec
    
    - path: cmd/
      linters:
        - gocyclo
        - mnd
        - depguard
    
    - path: example/
      linters:
        - mnd
        - goconst
        - depguard
        - errcheck
        - gosec
    
    - linters:
        - staticcheck
      text: "SA9003:"
    
    - linters:
        - lll
      source: "^//go:generate "

  exclude-use-default: false
  exclude:
    - 'declaration of "(err|ctx)" shadows declaration at'
    - 'package comment should be of the form'
  
  max-issues-per-linter: 50
  max-same-issues: 3
  new: false
