project_name: vrata

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: lt
    main: ./cmd/lt
    binary: lt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    goarm:
      - 6
      - 7
    ignore:
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64

archives:
  - id: default
    builds:
      - lt
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^refactor:"
      - "^style:"
      - Merge pull request
      - Merge branch

release:
  github:
    owner: korya
    name: vrata
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} {{.Version}}"

brews:
  - name: vrata
    ids:
      - default
    tap:
      owner: korya
      name: homebrew-tap
    folder: Formula
    homepage: "https://github.com/korya/vrata"
    description: "Go implementation of localtunnel - expose localhost to the world"
    license: "MIT"
    test: |
      system "#{bin}/lt --version"
    install: |
      bin.install "lt"

nfpms:
  - id: packages
    builds:
      - lt
    package_name: vrata
    vendor: korya
    homepage: "https://github.com/korya/vrata"
    maintainer: "korya <korya@example.com>"
    description: "Go implementation of localtunnel - expose localhost to the world"
    license: "MIT"
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin